version: 0.2

phases:
  install:
    commands:
      - aws s3 cp $s3_terraform terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version
  build:
    commands:
      - terraform init
      - terraform destroy