version: 0.2

env:
  secrets-manager:
    github_token: "arn:aws:secretsmanager:us-east-1:252265768975:secret:jaysosmc_github_access_token-tdzfcN"
phases:
  install:
    commands:
      - aws s3 cp $s3_terraform terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version
  build:
    commands:
      - terraform init
      - export TF_VAR_environment=$environment
      - export TF_VAR_lets_encrypt_email=$lets_encrypt_email
      - export TF_VAR_base_domain=$base_domain
      - export TF_VAR_test_controller_github_access_token=$github_token
      - export TF_VAR_ec2_public_key=$ec2_public_key
      - export TF_VAR_cert_arn=$cert_arn
      - export TF_VAR_hosted_zone_id=$hosted_zone_id
      - export TF_VAR_s3_build_bucket=$s3_build_bucket
      - export TF_VAR_test_controller_github_access_token=$test_controller_github_access_token
      - terraform plan -out ./tf-test.plan -var lets_encrypt_email=$lets_encrypt_email -var environment=$environment -var test_controller_github_access_token=$test_controller_github_access_token -var base_domain=$base_domain -var hosted_zone_id=$hosted_zone_id -input=false 
      - aws s3 cp ./tf-test.plan $s3_terraform_plan
